apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: super-api

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
- name: super-api-config
  files:
  - config.toml

secretGenerator:
- name: super-api-secret
  files:
  - cert/tls.crt
  - cert/tls.key
  type: "kubernetes.io/tls"
