name: Run Azure Login with OpenID Connect

on:
 workflow_dispatch

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/setup-kubectl@v1
      with:
        version: '1.20.9' # default is latest stable
        id: install
  
    - name: 'Run Azure CLI commands'
      run: |
          az aks get-credentials -n clu-vn -g rg-aks
          kubelogin convert-kubeconfig -l azurecli
          kubectl get nodes          
    