name: Publish Docker Image

on:
  release:
    types:
      - published

env:
  IMAGE_NAME: super

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # basic use of this action
          images: ghcr.io/gbaeke/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=tag
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Build
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }} 
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          cache-from: type=gha,src=/tmp/.buildx-cache
          cache-to: type=gha,mode=max,dest=/tmp/.buildx-cache

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - uses: sigstore/cosign-installer@main

      - name: Write signing key to disk (only needed for `cosign sign --key`)
        run: echo "${{ secrets.COSIGN_KEY }}" > cosign.key

      - name: Sign container image
        run: |
          cosign sign --key cosign.key \
            ghcr.io/gbaeke/super:${{ steps.get_version.outputs.VERSION }}
        env:
          COSIGN_PASSWORD: ""
          
      
